name: GitHub Actions to Deploy to Github Page
on: [push]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install 
      - name: Build bundle for gh-page
        uses: borales/actions-yarn@v4
        with:
          cmd: predeploy
      - name: Deploy to gh-page
        uses: borales/actions-yarn@v4
        with:
          cmd: deploy
